### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [chanson777/prj-rev-bwfs-tea-cozy#2]
_Grade: Exceeds Expectations_

Fantastic job on your project - you met the design requirements to a tee! In terms of your code, you did a phenomenal job. You used `div` tags in a meaningful way and your organizational skills really show off in the way you wrote your HTML. An area for improvement here is with your usage towards the `id` attribute. Seems as if you have them mixed up!

A recommendation here is to read the following article and to apply the concepts to your project. As projects get larger, this concept will help with the legibility and understanding of your code. Keep up the great work!
[id vs class](https://css-tricks.com/the-difference-between-id-and-class/)).

**Comment by chanson777** [comment]
Thank you so much for your very helpful review. Also, I appreciated reading the article you recommended on ID VS CLASS.  I think you were right.......in my brain I had it backwards! It "clicks" a little better now and I am hoping to try it out in this next project. This class is definitely fast paced. Just when I think I am making some headway.....I am behind again (or should I say still). I am throughly enjoying it though, and hope to keep studying even after the class has ended. Thank you again.......Crystal
